POSTTEST 7 - PENGENALAN TENSORFLOW
Nama : Wahyu Harry Saputra Sembiring
NIM : 2009106049
Kelas : Informatika A 2020

In [30]:
import tensorflow as tf

In [31]:
# Buat Tensor (5,5) dengan nilai Random
random_tensor = tf.Variable(tf.random.normal([5,5], mean=4, stddev=1, dtype=tf.float32))
random_tensor.read_value().numpy()

array([[4.854152 , 4.0945034, 4.265371 , 3.4155755, 5.8668737],
       [2.657279 , 5.1004663, 3.7438815, 4.2128067, 3.5088875],
       [4.651579 , 3.7660866, 4.7079253, 4.3662586, 4.728471 ],
       [4.4583926, 5.7127237, 3.7654843, 3.5786078, 2.8387287],
       [3.7054026, 4.0028815, 3.634648 , 4.6306643, 4.778719 ]],
      dtype=float32)

In [32]:
list = [[11,12,63,64,45],[21,32,34,54,65],[71,32,53,4,5],[91,52,63,54,95],[16,24,73,47,45]]
prime_tensor = tf.convert_to_tensor(list, dtype=tf.int64).numpy()

In [33]:
print("Ini adalah tampilan dimensi dari random tensor")
print(random_tensor.read_value().numpy())

print("\nIni adalah tampilan dimensi dari prime tensor")
print(prime_tensor)

Ini adalah tampilan dimensi dari random tensor
[[4.854152  4.0945034 4.265371  3.4155755 5.8668737]
 [2.657279  5.1004663 3.7438815 4.2128067 3.5088875]
 [4.651579  3.7660866 4.7079253 4.3662586 4.728471 ]
 [4.4583926 5.7127237 3.7654843 3.5786078 2.8387287]
 [3.7054026 4.0028815 3.634648  4.6306643 4.778719 ]]

Ini adalah tampilan dimensi dari prime tensor
[[11 12 63 64 45]
 [21 32 34 54 65]
 [71 32 53  4  5]
 [91 52 63 54 95]
 [16 24 73 47 45]]


In [34]:
# Penjumlahan
tf.add(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[15.854153, 16.094503, 67.26537 , 67.41557 , 50.866875],
       [23.65728 , 37.100468, 37.74388 , 58.212807, 68.50889 ],
       [75.65158 , 35.766087, 57.707924,  8.366259,  9.728471],
       [95.45839 , 57.712723, 66.76549 , 57.57861 , 97.83873 ],
       [19.705402, 28.002882, 76.63465 , 51.630665, 49.778717]],
      dtype=float32)>

In [35]:
# Pengurangan
tf.subtract(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -6.145848  ,  -7.9054966 , -58.73463   , -60.584423  ,
        -39.133125  ],
       [-18.34272   , -26.899534  , -30.256119  , -49.787193  ,
        -61.49111   ],
       [-66.34842   , -28.233913  , -48.292076  ,   0.36625862,
         -0.2715292 ],
       [-86.54161   , -46.287277  , -59.234516  , -50.42139   ,
        -92.16127   ],
       [-12.294598  , -19.997118  , -69.36535   , -42.369335  ,
        -40.221283  ]], dtype=float32)>

In [36]:
# Perkalian
tf.multiply(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 53.395676,  49.13404 , 268.71835 , 218.59683 , 264.0093  ],
       [ 55.80286 , 163.21492 , 127.29197 , 227.49156 , 228.07768 ],
       [330.26212 , 120.51477 , 249.52003 ,  17.465034,  23.642353],
       [405.7137  , 297.06165 , 237.22551 , 193.24483 , 269.67923 ],
       [ 59.28644 ,  96.06915 , 265.3293  , 217.64122 , 215.04236 ]],
      dtype=float32)>

In [37]:
# Pembagian
tf.divide(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.44128656, 0.3412086 , 0.0677043 , 0.05336837, 0.13037497],
       [0.1265371 , 0.15938957, 0.11011416, 0.07801494, 0.05398288],
       [0.0655152 , 0.11769021, 0.08882878, 1.0915647 , 0.94569415],
       [0.04899333, 0.10986007, 0.05976959, 0.06627052, 0.02988135],
       [0.23158766, 0.16678673, 0.0497897 , 0.09852477, 0.10619375]],
      dtype=float32)>

In [38]:
# Logaritma
tf.math.log(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1.5798345, 1.4096454, 1.4505291, 1.228346 , 1.7693219],
       [0.9773027, 1.629332 , 1.320123 , 1.4381291, 1.2552991],
       [1.5372066, 1.3260365, 1.5492473, 1.4739065, 1.5536019],
       [1.4947883, 1.7426959, 1.3258765, 1.2749739, 1.0433563],
       [1.3097919, 1.3870145, 1.2905123, 1.5327003, 1.5641725]],
      dtype=float32)>

In [39]:
#Perpangkatan
tf.pow(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[3.5257156e+07, 2.2203162e+07,           inf, 1.3857631e+34,
        3.7870705e+34],
       [8.1880467e+08, 4.4006428e+22, 3.1113657e+19, 5.3316641e+33,
        2.7290665e+35],
       [          inf, 2.6821904e+18, 4.5705340e+35, 3.6344427e+02,
        2.3637610e+03],
       [          inf,           inf, 1.8910945e+36, 7.9535607e+29,
                  inf],
       [1.2628927e+09, 2.8638198e+14,           inf, 1.9285691e+31,
        3.7069525e+30]], dtype=float32)>

In [40]:
tf.matmul(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 846.90894,  644.1807 , 1314.5524 , 1009.0145 , 1094.3954 ],
       [ 841.6631 ,  618.1857 , 1060.8058 ,  852.87585, 1027.9438 ],
       [ 937.5029 ,  667.51605, 1290.8691 ,  977.9175 , 1105.232  ],
       [ 807.4319 ,  611.0205 , 1107.3615 ,  935.5512 , 1058.4927 ],
       [ 880.72986,  644.3496 , 1202.753  ,  942.49567, 1100.0591 ]],
      dtype=float32)>

In [41]:
tf.argmax(random_tensor, axis=0).numpy()

array([0, 3, 2, 4, 0])

In [42]:
tf.argmin(random_tensor, axis=0).numpy()

array([1, 2, 4, 0, 3])

In [43]:
print(f"Size Awal : {random_tensor.shape} {prime_tensor.shape}" )

Size Awal : (5, 5) (5, 5)


In [44]:
concat_tensor_1 = tf.concat([random_tensor, prime_tensor], axis=0)
concat_tensor_2 = tf.concat([random_tensor, prime_tensor], axis=1)
print(f"Size yang sudah di concat (axis = 0) : {concat_tensor_1.shape}")
print(f"Size yang sudah di concat (axis = 1) : {concat_tensor_2.shape}")

Size yang sudah di concat (axis = 0) : (10, 5)
Size yang sudah di concat (axis = 1) : (5, 10)


In [45]:
# random_tensor descending sorting
tf.sort(random_tensor, direction="DESCENDING").numpy()

array([[5.8668737, 4.854152 , 4.265371 , 4.0945034, 3.4155755],
       [5.1004663, 4.2128067, 3.7438815, 3.5088875, 2.657279 ],
       [4.728471 , 4.7079253, 4.651579 , 4.3662586, 3.7660866],
       [5.7127237, 4.4583926, 3.7654843, 3.5786078, 2.8387287],
       [4.778719 , 4.6306643, 4.0028815, 3.7054026, 3.634648 ]],
      dtype=float32)

In [46]:
# random_tensor ascending sorting
tf.sort(random_tensor, direction="ASCENDING").numpy()

array([[3.4155755, 4.0945034, 4.265371 , 4.854152 , 5.8668737],
       [2.657279 , 3.5088875, 3.7438815, 4.2128067, 5.1004663],
       [3.7660866, 4.3662586, 4.651579 , 4.7079253, 4.728471 ],
       [2.8387287, 3.5786078, 3.7654843, 4.4583926, 5.7127237],
       [3.634648 , 3.7054026, 4.0028815, 4.6306643, 4.778719 ]],
      dtype=float32)

In [47]:
# prime_tensor descending sorting
tf.sort(prime_tensor, direction="DESCENDING").numpy()

array([[64, 63, 45, 12, 11],
       [65, 54, 34, 32, 21],
       [71, 53, 32,  5,  4],
       [95, 91, 63, 54, 52],
       [73, 47, 45, 24, 16]])

In [29]:
# prime_tensor ascending sorting
tf.sort(prime_tensor, direction="ASCENDING").numpy()

array([[11, 12, 45, 63, 64],
       [21, 32, 34, 54, 65],
       [ 4,  5, 32, 53, 71],
       [52, 54, 63, 91, 95],
       [16, 24, 45, 47, 73]])