### POSTTEST 8
### Nama     : Wahyu Harry Saputra Sembiring
### NIM      : 2009106049
### Kelas    : Informatika A 2020 (A2)

In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import warnings
from plotly.subplots import make_subplots
from datetime import datetime
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import MinMaxScaler

In [ ]:
dateparse = lambda x: datetime.strptime(x, '%d/%m/%Y')

df = pd.read_csv("https://raw.githubusercontent.com/wahyusaputra073/Prediksi_Beras/main/beras_kaltim.csv",
                 parse_dates=["Komoditas(Rp)"],
                 date_parser=dateparse,
                 index_col=["Komoditas(Rp)"])

#Ubah nama index
df.index.names = ['Date']

In [ ]:
df.head()

Beras  Beras Kualitas Bawah I (kg)  Beras Kualitas Bawah II (kg)  \
Date                                                                           
2021-01-04  12350                        10850                         10700   
2021-01-05  12350                        10850                         10700   
2021-01-06  12350                        10850                         10700   
2021-01-07  12350                        10850                         10700   
2021-01-08  12350                        10850                         10700   

            Beras Kualitas Medium I (kg)  Beras Kualitas Medium II (kg)  \
Date                                                                      
2021-01-04                         12650                          12400   
2021-01-05                         12650                          12400   
2021-01-06                         12650                          12400   
2021-01-07                         12650                          12400   
2021-01-08                         12650                          12400   

            Beras Kualitas Super I (kg)  Beras Kualitas Super II (kg)  
Date                                                                   
2021-01-04                        13950                         13400  
2021-01-05                        13950                         13400  
2021-01-06                        13950                         13400  
2021-01-07                        13950                         13400  
2021-01-08                        13950                         13400

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 429 entries, 2021-01-04 to 2022-09-30
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Beras                          429 non-null    int64
 1   Beras Kualitas Bawah I (kg)    429 non-null    int64
 2   Beras Kualitas Bawah II (kg)   429 non-null    int64
 3   Beras Kualitas Medium I (kg)   429 non-null    int64
 4   Beras Kualitas Medium II (kg)  429 non-null    int64
 5   Beras Kualitas Super I (kg)    429 non-null    int64
 6   Beras Kualitas Super II (kg)   429 non-null    int64
dtypes: int64(7)
memory usage: 26.8 KB


In [ ]:
df.describe().T

count          mean         std      min  \
Beras                          429.0  12309.906760  146.735475  12050.0   
Beras Kualitas Bawah I (kg)    429.0  10957.575758  269.812495  10500.0   
Beras Kualitas Bawah II (kg)   429.0  10881.002331  206.679743  10650.0   
Beras Kualitas Medium I (kg)   429.0  12515.734266  198.218077  11400.0   
Beras Kualitas Medium II (kg)  429.0  12431.934732  157.762496  12150.0   
Beras Kualitas Super I (kg)    429.0  13812.470862  141.014191  13500.0   
Beras Kualitas Super II (kg)   429.0  13203.496503  551.706688  12650.0   

                                   25%      50%      75%      max  
Beras                          12150.0  12350.0  12350.0  14050.0  
Beras Kualitas Bawah I (kg)    10750.0  10850.0  11100.0  11600.0  
Beras Kualitas Bawah II (kg)   10750.0  10750.0  11100.0  11400.0  
Beras Kualitas Medium I (kg)   12350.0  12550.0  12650.0  12850.0  
Beras Kualitas Medium II (kg)  12250.0  12450.0  12500.0  12950.0  
Beras Kualitas Super I (kg)    13650.0  13850.0  13950.0  14050.0  
Beras Kualitas Super II (kg)   13000.0  13100.0  13500.0  23650.0

In [ ]:
print(f"Shape Data {df.shape}")

Shape Data (429, 7)


### Mengelompokkan Data

In [ ]:
df_resample_month = df.resample('M').mean()

In [ ]:
pio.templates.default = "plotly_dark"

fig = go.Figure()
fig.add_trace(go.Box(y=df_resample_month["Beras Kualitas Bawah I (kg)"], name='Beras Kualitas Bawah I'))
fig.add_trace(go.Box(y=df_resample_month["Beras Kualitas Bawah II (kg)"], name='Beras Kualitas Bawah II'))
fig.add_trace(go.Box(y=df_resample_month["Beras Kualitas Medium I (kg)"], name='Beras Kualitas Medium I'))
fig.add_trace(go.Box(y=df_resample_month["Beras Kualitas Medium II (kg)"], name='Beras Kualitas Medium II'))
fig.add_trace(go.Box(y=df_resample_month["Beras Kualitas Super I (kg)"], name="Beras Kualitas Super I"))
fig.add_trace(go.Box(y=df_resample_month["Beras Kualitas Super II (kg)"], name='Beras Kualitas Super II'))


fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide',xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linewidth=2,
        ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
        ),
    ),
    title_text='Harga Jenis Beras',
    xaxis_title="Jenis Beras",
    yaxis_title="Harga Beras/Kg",
    )
fig.show()

In [ ]:
# Beras Kualitas Bawah
fig = go.Figure()
fig.add_trace(go.Box(y=df_resample_month["Beras Kualitas Bawah I (kg)"], name='Beras Kualitas Bawah I'))
fig.add_trace(go.Box(y=df_resample_month["Beras Kualitas Bawah II (kg)"], name='Beras Kualitas Bawah II'))

fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide',xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linewidth=2,
        ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
        ),
    ),
    title_text='Harga Jenis Beras Kualitas Bawah',
    xaxis_title="Jenis Beras",
    yaxis_title="Harga Beras/Kg",
    )
fig.show()

# Beras Kualitas Medium
fig = go.Figure()
fig.add_trace(go.Box(y=df_resample_month["Beras Kualitas Medium I (kg)"], name='Beras Kualitas Medium I'))
fig.add_trace(go.Box(y=df_resample_month["Beras Kualitas Medium II (kg)"], name='Beras Kualitas Medium II'))

fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide',xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linewidth=2,
        ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
        ),
    ),
    title_text='Harga Jenis Beras Kualitas Medium',
    xaxis_title="Jenis Beras",
    yaxis_title="Harga Beras/Kg",
    )
fig.show()


# Beras Kualitas Super
fig = go.Figure()
fig.add_trace(go.Box(y=df_resample_month["Beras Kualitas Super I (kg)"], name="Beras Kualitas Super I"))
fig.add_trace(go.Box(y=df_resample_month["Beras Kualitas Super II (kg)"], name='Beras Kualitas Super II'))

fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide',xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linewidth=2,
        ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
        ),
    ),
    title_text='Harga Jenis Beras Kualitas Super',
    xaxis_title="Jenis Beras",
    yaxis_title="Harga Beras/Kg",
    )
fig.show()

In [ ]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    y = df_resample_month["Beras Kualitas Bawah I (kg)"],
    x = df_resample_month.index,
    connectgaps=True,
    name="Beras Kualitas Bawah I",
    legendgrouptitle_text="Kualitas Bawah",
    legendgroup='group'
))

fig.add_trace(go.Scatter(
    y = df_resample_month["Beras Kualitas Bawah II (kg)"],
    x = df_resample_month.index,
    connectgaps=True,
    name="Beras Kualitas Bawah II",
    legendgrouptitle_text="Kualitas Bawah",
    legendgroup='group'
))

fig.add_trace(go.Scatter(
    y = df_resample_month["Beras Kualitas Medium I (kg)"],
    x = df_resample_month.index,
    connectgaps=True,
    name="Beras Kualitas Medium I",
    legendgrouptitle_text="Kualitas Medium",
    legendgroup='group1'
))
fig.add_trace(go.Scatter(
    y = df_resample_month["Beras Kualitas Medium II (kg)"],
    x = df_resample_month.index,
    connectgaps=True,
    legendgrouptitle_text="Kualitas Medium",
    name="Beras Kualitas Medium II",
    legendgroup='group1'
))


#Kualitas Super
fig.add_trace(go.Scatter(
    y = df_resample_month["Beras Kualitas Super I (kg)"],
    x = df_resample_month.index,
    connectgaps=True,
    name="Beras Kualitas Super I",
    legendgrouptitle_text="Kualitas Super",
    legendgroup='group2'
))
fig.add_trace(go.Scatter(
    y = df_resample_month["Beras Kualitas Super II (kg)"],
    x = df_resample_month.index,
    connectgaps=True,
    legendgrouptitle_text="Kualitas Super",
    name="Beras Kualitas Super II",
    legendgroup='group2'
))

fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide',xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linewidth=2,
        ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
        ),
    ),
    title_text='Tren Harga Tiap Jenis Beras',
    xaxis_title="Tanggal",
    yaxis_title="Harga/Kg (Rp)"
    )

### MODELLING

**Split Data**

In [ ]:
print(f"Len Data         : {len(df)}")
print(f"Len training set : {round(len(df) * 0.8)}")
print(f"Len testing set  : {round(len(df) * 0.2)}")

Len Data         : 429
Len training set : 343
Len testing set  : 86


In [ ]:
train = df.iloc[:343]
test = df.iloc[343:]
len(test)

86

In [ ]:
train_BerasBawahI = train[["Beras Kualitas Bawah I (kg)"]]
test_BerasBawahI = test[["Beras Kualitas Bawah I (kg)"]]

In [ ]:
scaler = MinMaxScaler()

scaled_train_BerasBawahI = scaler.fit_transform(train_BerasBawahI)
scaled_test_BerasBawahI = scaler.fit_transform(test_BerasBawahI)

In [ ]:
from keras.preprocessing.sequence import TimeseriesGenerator

scaled_train_BerasBawahI = scaled_train_BerasBawahI[:,0]
scaled_test_BerasBawahI = scaled_test_BerasBawahI[:,0]

n_input = 30

generator = TimeseriesGenerator(scaled_train_BerasBawahI, scaled_train_BerasBawahI, length=n_input,batch_size=1)

In [ ]:
for i in range(3):
    x, y = generator[i]
    print('%s => %s' % (x, y))
    print("\n")

[[0.41176471 0.41176471 0.41176471 0.41176471 0.41176471 0.41176471
  0.41176471 0.41176471 0.41176471 0.41176471 0.41176471 0.41176471
  0.41176471 0.41176471 0.41176471 0.41176471 0.41176471 0.41176471
  0.41176471 0.41176471 0.41176471 0.41176471 0.41176471 0.41176471
  0.41176471 0.41176471 0.41176471 0.41176471 0.41176471 0.41176471]] => [0.41176471]


[[0.41176471 0.41176471 0.41176471 0.41176471 0.41176471 0.41176471
  0.41176471 0.41176471 0.41176471 0.41176471 0.41176471 0.41176471
  0.41176471 0.41176471 0.41176471 0.41176471 0.41176471 0.41176471
  0.41176471 0.41176471 0.41176471 0.41176471 0.41176471 0.41176471
  0.41176471 0.41176471 0.41176471 0.41176471 0.41176471 0.41176471]] => [0.41176471]


[[0.41176471 0.41176471 0.41176471 0.41176471 0.41176471 0.41176471
  0.41176471 0.41176471 0.41176471 0.41176471 0.41176471 0.41176471
  0.41176471 0.41176471 0.41176471 0.41176471 0.41176471 0.41176471
  0.41176471 0.41176471 0.41176471 0.41176471 0.41176471 0.41176471
  0.4117

**Long Short Term Memory (LSTM)**

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

In [ ]:
#Buat model
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(n_input, 1)))
model.add(Dense(100,activation='relu'))
model.add(Dense(1,activation='relu'))

model.compile(optimizer='adam', loss='mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 100)               40800     
                                                                 
 dense (Dense)               (None, 100)               10100     
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 51,001
Trainable params: 51,001
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

# Define a callback to monitor val_accuracy
monitor_loss = EarlyStopping(monitor='loss', patience=8)

In [ ]:
#Latih Model
model.fit(generator, steps_per_epoch=1, epochs=50, verbose=1)

Epoch 1/50
1/1 [==============================] - 2s 2s/step - loss: 0.1696
Epoch 2/50
1/1 [==============================] - 0s 28ms/step - loss: 0.4950
Epoch 3/50
1/1 [==============================] - 0s 30ms/step - loss: 0.0025
Epoch 4/50
1/1 [==============================] - 0s 31ms/step - loss: 0.0435
Epoch 5/50
1/1 [==============================] - 0s 29ms/step - loss: 0.3998
Epoch 6/50
1/1 [==============================] - 0s 30ms/step - loss: 0.3730
Epoch 7/50
1/1 [==============================] - 0s 32ms/step - loss: 0.3262
Epoch 8/50
1/1 [==============================] - 0s 28ms/step - loss: 0.0903
Epoch 9/50
1/1 [==============================] - 0s 29ms/step - loss: 0.0230
Epoch 10/50
1/1 [==============================] - 0s 29ms/step - loss: 0.0698
Epoch 11/50
1/1 [==============================] - 0s 39ms/step - loss: 0.0179
Epoch 12/50
1/1 [==============================] - 0s 32ms/step - loss: 0.0017
Epoch 13/50
1/1 [==============================] - 0s 33ms/step

In [ ]:
last_line_train = scaled_train_BerasBawahI[-n_input:]
last_line_train = last_line_train.reshape(1,30,1)

model.predict(last_line_train)

1/1 [==============================] - 1s 1s/step


array([[0.8063091]], dtype=float32)

In [ ]:
test_pred = []

first_eval_batch = scaled_train_BerasBawahI[-n_input:]
cur_batch = first_eval_batch.reshape(1,30,1)


for i in range(len(scaled_test_BerasBawahI)):
    #Dapatkan Prediksi dari nilai pertama untuk tiap batch
    current_pred = model.predict(cur_batch)[0]

    #Append hasil prediksi ke array
    test_pred.append(current_pred)

    #Update nilai tiap batch
    cur_batch = np.append(cur_batch[:,1:,:],[[current_pred]],axis=1)

1/1 [==============================] - 0s 20ms/step


In [ ]:
#Prediksi 5 hari pertama
test_pred[0:5]

[array([0.8063091], dtype=float32),
 array([0.7958483], dtype=float32),
 array([0.7854509], dtype=float32),
 array([0.7749772], dtype=float32),
 array([0.76460147], dtype=float32)]

In [ ]:
prediction = scaler.inverse_transform(test_pred)
test_BerasBawahI["Prediction"] = prediction

test_BerasBawahI.tail()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



Beras Kualitas Bawah I (kg)    Prediction
Date                                                 
2022-09-26                        11600  11438.872918
2022-09-27                        11600  11438.710681
2022-09-28                        11600  11438.555479
2022-09-29                        11600  11438.407001
2022-09-30                        11600  11438.264987

**Visualisasikan**

In [ ]:
test_BerasBawahI_M = test_BerasBawahI.resample('M').mean()

In [ ]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    y = test_BerasBawahI_M["Beras Kualitas Bawah I (kg)"],
    x = test_BerasBawahI_M.index,
    connectgaps=True,
    name="Hasil Aktual",
    legendgrouptitle_text="Kualitas Bawah",
    legendgroup='group'
))

fig.add_trace(go.Scatter(
    y = test_BerasBawahI_M["Prediction"],
    x = test_BerasBawahI_M.index,
    connectgaps=True,
    name="Hasil Prediksi",
))


fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide',xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linewidth=2,
        ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
        ),
    ),
    title_text='Perbandingan Prediksi vs Aktual',
    xaxis_title="Tanggal",
    yaxis_title="Harga/Kg (Rp)"
    )

**Prediksi**

Prediksikan Harga Beras selama 1 bulan kedepan

In [ ]:
#Ambil 30 data terakhir
forecast_berasbawahI = test_BerasBawahI.iloc[-30:,0]

In [ ]:
ss = MinMaxScaler()
#Lakukan Scaling
scaled_forecast_BerasBawahI = ss.fit_transform(forecast_berasbawahI.values.reshape(-1,1))

In [ ]:
#Lakukan prediksi
test_pred_forecast = []

first_eval_batch = scaled_forecast_BerasBawahI[-30:]
cur_batch = first_eval_batch.reshape(1,30,1)


for i in range(30):
    #Dapatkan Prediksi dari nilai pertama untuk tiap batch
    current_pred = model.predict(cur_batch)[0]

    #Append hasil prediksi ke array
    test_pred_forecast.append(current_pred)

    #Update nilai tiap batch
    cur_batch = np.append(cur_batch[:,1:,:],[[current_pred]],axis=1)

1/1 [==============================] - 0s 25ms/step


In [ ]:
prediction_forecast = ss.inverse_transform(test_pred_forecast)
prediction_forecast = prediction_forecast.flatten()

In [ ]:
test_BerasBawahI.drop("Prediction",axis=1,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [ ]:
#Buat DataFrame Baru
date = pd.date_range(start='2022-10-01', periods=30)

df2 = pd.DataFrame({
    "Beras Kualitas Bawah I (kg)" : prediction_forecast
}, index=date)


#Gabungkan Data
dfpred = pd.concat([test_BerasBawahI,df2])

In [ ]:
import seaborn as sns

fig = go.Figure()

fig.add_trace(go.Scatter(
    y = df2["Beras Kualitas Bawah I (kg)"],
    x = df2.index,
    connectgaps=True,
    name="Hasil Prediksi",
))

fig.add_trace(go.Scatter(
    y = test_BerasBawahI["Beras Kualitas Bawah I (kg)"],
    x = test_BerasBawahI.index,
    connectgaps=True,
    name="Hasil Aktual",
))


fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide',xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linewidth=2,
        ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
        ),
    ),
    title_text='Perbandingan Prediksi vs Aktual',
    xaxis_title="Tanggal",
    yaxis_title="Harga/Kg (Rp)"
    )